BOX_IMAGE = "centos/6"
NODE_COUNT=1
 
Vagrant.configure("2") do |config|
    config.vm.define "master" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "master"
      subconfig.vm.network :private_network, ip: "10.0.0.10"
    end

    
    (1..NODE_COUNT).each do |i|
      config.vm.define "node#{i}" do |subconfig|
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.hostname = "node#{i}"
        subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
      end
    end
  
    # Install avahi on all machines  
    config.vm.provision "shell",  path: "install_avahi.sh" 
end
